---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namesapce: argocd
  labels:
    application: keycloak
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: sre
  source:
    directory:
      jsonnet: {}
      recurse: false
    path: ./sre/keycloak
    repoURL: https://github.com/mmatur/traefik-enterprise-demo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
