---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namesapce: argocd
  labels:
    application: monitoring
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: sre
  source:
    directory:
      jsonnet: {}
      recurse: false
    path: ./sre/monitoring
    repoURL: https://github.com/mmatur/traefik-enterprise-demo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
