
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namesapce: argocd
  labels:
    application: app
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  project: app
  source:
    directory:
      jsonnet: {}
      recurse: false
    path: ./dev/app
    repoURL: https://github.com/mmatur/traefik-enterprise-demo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
